# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	1791825515	sid	19028517e1d1466cb1e0e005f701e463c12b5d2772aa8c3f4345a2215e6fa719
